apiVersion: "talks.avolens.com/v1beta1"
kind: "Troopers2023Talk"
metadata:
  name: "talk-18"
  namespace: "tr23"
spec:
  title: "So You Performed A Forest Recovery. How Do You Reconnect Your AD Again With Azure AD?"
  speaker:
  - name: "Jorge de Almeida Pinto"
    canTalk: true
  status:
    accepted: true
    track: "Active Directory & Azure Security"
    timestamp: 1687965300.0