apiVersion: "talks.avolens.com/v1beta1"
kind: "Troopers2023Talk"
metadata:
  name: "talk-32"
  namespace: "tr23"
spec:
  title: "Beyond Java: Obfuscating Android Apps with Purely Native Code"
  speaker:
  - name: "Laurie Kirk"
    canTalk: true
  status:
    accepted: true
    track: "Track 3"
    timestamp: 1688031000.0