apiVersion: v1
kind: Pod
metadata:
  name: unprivileged-pod
  namespace: secure-namespace
  labels:
    app.kubernetes.io/name: unprivileged-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: container
    image: raesene/alpine-containertools
    command: ["sh"]
    args: ["-c", "sleep 999999999"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
        add: ["NET_BIND_SERVICE"]
      runAsNonRoot: true
      seccompProfile:
        type: "RuntimeDefault"
